### ISSUE TITLE
App作成に利用するFrameworkを決定する

### ISSUE THREAD

**Issue by amacbee** [PyLadiesTokyo/girls-tech-fes#1]
いま一番有望な候補はBottleかな

**Comment by nobolis** [comment]
Wakari.ioについて調べたところ（Tools>Anaconda Environments）、FlaskとTornadoは入っているみたいです。Bottleは残念ながらなかった。

**Comment by nobolis** [comment]
FYI
2014年 Webアプリケーションフレームワークトレンド（PHP / Java / Ruby / Python / Perl
http://qiita.com/shukotang/items/055058b33b553b48c164

**Comment by amacbee** [comment]
Frameworkの中身を説明したいみたいな需要が出てきたときはbottle.py (!?)一つで構成されてるBottleが良い（＝環境構築こちらでするとしたら用意も楽）・・・的な感じでBottleかなと考えてたんですが，「複数台のWindowsマシンで作業させる」ハードル高すぎなので，上記の仲ならFlaskとか良いかもですね〜〜（マシン性能鑑みると動作の遅さがちょっと怖いですが）
Tornadoの方は実はちゃんと開発したことないので良く分かってませんｗ

**Comment by amacbee** [comment]
利用するWeb FrameworkはTornadoでいきます
