### ISSUE TITLE
東大広報やAnita Borgとのメール引き継ぎ

### ISSUE THREAD

**Issue by amacbee** [PyLadiesTokyo/girls-tech-fes#13]
@nobolis さんに，これまでのやりとりのメールを転送したり，向こうの担当者に窓口の方として紹介する

**Comment by amacbee** [comment]
issue共有として， @nobolis さんも割り振ります

**Comment by nobolis** [comment]
紹介よろしくお願いします。
- 今後のメールのやりとりは@macbeeにccとかでいいでしょうか？
- どこかにまとめてメール保存とかしますか？

**Comment by amacbee** [comment]
tokyo@pyladies.com にCCして頂けたらと思います！

**Comment by nobolis** [comment]
了解です。
やりとり自体は自分のメアドでですかね。

**Comment by mahya8585** [comment]
#5  
（確認内容リストをリンクしておきます

**Comment by amacbee** [comment]
やりとりメール全ての転送done.

**Comment by amacbee** [comment]
担当者引き継ぎのメール送信done.
@nobolis さん，後はよろしくお願いします！

**Comment by nobolis** [comment]
メール転送と引き継ぎメールありがとうございました。メール確認しました。
あとで自己紹介メールしておきます。

**Comment by amacbee** [comment]
よろしくお願いします〜
その際可能であれば先日話した確認事項について先方にお問い合わせ下さいmm

**Comment by nobolis** [comment]
@amacbee
#5の件ですね。了解ですノ

**Comment by nobolis** [comment]
[Done] メール内容確認
[Done] ご挨拶メール送信（確認事項は別メールにて送信予定）

**Comment by nobolis** [comment]
以降、以下のルールで連絡事項を管理します：  
東大広報/Anita Borgへ質問したい場合 -->  #24 へ投稿  
東大広報/Anita Borgから質問がきた場合 --> #25 へ投稿

**Comment by nobolis** [comment]
返信がないので、こちらから送ったメールが迷惑メールになっているかも？
職場のメアドから連絡しようか、検討中。
（あと1日待ってみる予定）

**Comment by amacbee** [comment]
相手からの返信ペースはいつもゆっくりめです．
2〜3日は待ってみた方が良いと思いますε=ε=ε=┌(;*´Д`)ﾉ

**Comment by nobolis** [comment]
ゆっくりめ or 迷惑メール行きのどちらかなーと思ったのですが、ゆっくりめの方でしたか。
じゃあ今週いっぱい待って、もし連絡が来なかったら月曜日（2/9）に連絡してみます。

**Comment by amacbee** [comment]
:star:

**Comment by nobolis** [comment]
返信きた。ゆっくりめでしたね。
