### ISSUE TITLE
Tシャツを作る

### ISSUE THREAD

**Issue by uni-q** [PyLadiesTokyo/girls-tech-fes#14]
PyLadies TokyoのTシャツ

やることリスト
1. デザイン作る（03/01までにFIX）
2. スタッフに共有・ヒアリング
3. デザイン調節
4. Tシャツ業社の選定
5. Tシャツ業社に発注
6. Tシャツでかかった経費をZaimに記入する

**Comment by uni-q** [comment]
2/15までにスケジュールをひくのと、あと業者を選定します。

**Comment by amacbee** [comment]
よろしくお願いします〜

**Comment by uni-q** [comment]
2/15作業できませんでした。
2/20作業する予定。

**Comment by amacbee** [comment]
- イベントでTシャツを着たい方を募る
  - 純粋に欲しい人も募る --> Slack？
  - 今回の分は個人費で
- 業者・枚数・予算について --> @maaya8585 さんと相談する

**Comment by uni-q** [comment]
- スタッフ数いまのところ8人。10枚発注する。
- 割高になるようだったら、もうちょっと多めに作って、余ったものを売るとか。
- 20とか見積もれるかもしれない。
- 見積もっておおよその価格が分かったら、Slackで欲しい人つのってみる。Tシャツだけ欲しいという人もいるかもしれないので。
- 台湾のAPECでも使いたい

**Comment by amacbee** [comment]
会社でオリジナルパーカーを作成するときに利用したところ
http://tmix.jp/design/preview?parent_item_id=154390

**Comment by uni-q** [comment]
pycon jp で使ってる業社（大量発注する系）
http://www.firstball.net/simulation/item.php?cate=1

やすそうなところ
http://www.esgraphic.co.jp/item/detail/261

**Comment by uni-q** [comment]
見積もりメモ
http://tmix.jp/item/ladys/tshirt_wcn
- 20枚〜29枚：2612.4円
- 10枚：2800円

**Comment by mahya8585** [comment]
20枚発注することに決定（余った分は手売り・・・します！）

【確定枚数】
S ：1
M：4
L：2

【検討中】
S：1
M：0
L：1

というわけで・・・・

【購入枚数】
S：4
M：10
L：6

でおねがいします！

**Comment by saorio** [comment]
まあやさん

自分がどっちのサイズで申し込んだか忘れてしまった…Sサイズ希望です。

2015年3月18日水曜日、maaya ishidanotifications@github.comさんは書きました:

**Comment by mahya8585** [comment]
@saorio 大丈夫ですよ！Sで登録いただいてます！

**Comment by saorio** [comment]
そうでしたか。失礼致しました。
ありがとうございます。

2015年3月18日水曜日、maaya ishidanotifications@github.comさんは書きました:

**Comment by uni-q** [comment]
発注した
