### ISSUE TITLE
当日スタッフの割り振りを決める

### ISSUE THREAD

**Issue by uni-q** [PyLadiesTokyo/girls-tech-fes#19]
# 目的

当日の担当を決める

https://github.com/PyLadiesTokyo/girls-tech-fes/issues/4#issuecomment-72348762

> 【メモ】
> 当日担当割り振りは2月21日に決定する
- 受付
- 講師 / 進行
- 講師補佐
- タイムキーピング / 広報
# 手順
1. まずはアンケートに答える http://goo.gl/forms/enQnUczmMT
2. アンケートでやりたい担当に立候補
3. 割り振りする
4. 決められたスタッフまとめはこちら https://docs.google.com/a/pyladies.com/document/d/19zHhcEtF6KBMH3qi4I05hkHV6M9bVkEbYLolxbzsXDM/edit
# 関連issue
#4

**Comment by uni-q** [comment]
ドキュメント見ました。
当日、私は受付・その他雑用？…しか出来なさそうなので、それに立候補します。(；・∀・)

**Comment by amacbee** [comment]
暫定的に決定
https://docs.google.com/document/d/19zHhcEtF6KBMH3qi4I05hkHV6M9bVkEbYLolxbzsXDM/edit
