### ISSUE TITLE
Appの作成環境を決定する

### ISSUE THREAD

**Issue by amacbee** [PyLadiesTokyo/girls-tech-fes#2]
Windows Serverを利用するか，Online Codingの出来るServiceを検討するか

**Comment by amacbee** [comment]
IPython Notebook Server たてるの凄く簡単なので，IPython Notebook as a Web Platform的なやつを調べてみたのですが，以下のstackoverflow他で見る限り微妙でした．
http://stackoverflow.com/questions/15691479/ipython-notebook-as-a-web-tool-dev-platform

一応こういうrepoもあります
https://github.com/minrk/singlecell

**Comment by amacbee** [comment]
Slackで出てた意見 @uni-q
20人以上超えてもうまく動くか検証したい感じ(ΦωΦ)

> Heroku とかどうだろう

**Comment by nobolis** [comment]
Online codingするツールについて、wakariというサービスを教えてもらいました：
https://wakari.io/wakari

アカウント作るだけで利用できるみたいです。

**Comment by nobolis** [comment]
さっそく記事かいてくれて教えてくれたのでシェア：
http://librabuch.jp/2015/01/wakari-io/

**Comment by amacbee** [comment]
Wakari.io，データ解析用のイメージ強くてアカウント持ってたのに完全に失念してましたw
ありがとうございます！
アカウント一つで複数のWeb ApplicationたてられるならPyLadies Tokyoのアカウントとして利用してみようかな。。。本日の作業で確認したい感じ．

**Comment by amacbee** [comment]
wakari.io さん使って見てるんですが，以下の状態から反応がない。。。

> LOADING...

一つのアカウントだと512Mしかメモリがないので，これでやるとしたら人数分のアカウントを作成する必要がありそう．ShellやIPython Notebookはいけるけど，Webブラウザで結果を確認する方法が明示されてなくてやり方を模索中．

**Comment by mahya8585** [comment]
https://files.slack.com/files-pri/T02RSHV5R-F03H2L9RE/slack_for_ios_upload.jpg

設計たたき台写真（みれなかったらごめんね）

**Comment by amacbee** [comment]
wakari.io 複数人で使うにはちょっと難がある感じだったので，コード書いたりする環境としてIPython Notebook Server，アプリケーションを動かすフレームワークとしてTornadoで考え中．
ただ事前準備が可能であれば個々のマシンにソフトとか色々入れられるので，その辺りがはっきり次第再考したい感じ．

**Comment by amacbee** [comment]
とりあえず以下のissue待ちで
ref. #31

**Comment by amacbee** [comment]
Beakerも良さそうだけど試してる暇ないな。。。
http://beakernotebook.com/

**Comment by amacbee** [comment]
#31 の結果，前日にPCの環境を構築できることがわかった
よって以下のソフトを個々のPCに導入する
- Python 2.7.9
- PyCharm
  - pipでtornadoを導入
