### ISSUE TITLE
スタッフ作業日のconnpassイベントを作成する

### ISSUE THREAD

**Issue by amacbee** [PyLadiesTokyo/girls-tech-fes#20]
スタッフ作業日のconnpassイベントを作成する #8 
参考：http://pyconjp.connpass.com/event/11104/

日程は以下の通り
- 2/21(土) 14:00〜17:00
- 3/21(土) 14:00〜17:00
- 3/28(土) 13:00〜17:00

**Comment by mahya8585** [comment]
@amacbee とりあえず一番直近の2/21分のたたき台を下書きにいれてみたので、
レビューお願いできますか？
指摘事項マージした上で他２日分＆当日も同様作成します。

**Comment by amacbee** [comment]
> 女子もしくは女性であること
> 「女性であること」で良いと思います．

```
Girls Tech Fesに参加するPyLadies Tokyoのスタッフが集まって作業をする日です．
GithubのIssueをベースに個々にふられているタスクを消化します．

具体的に何をするのか分からないけど興味がある！という方もお気軽にご参加下さい．
```

といった一文を最初に入れると良いかなと思います．
その後に，「Girls Tech Fesとは？」「スタッフとして参加して頂ける人を募集しています」といった項目を作るとより分かりやすいかなと思います．
よろしくお願いします！

**Comment by mahya8585** [comment]
@amacbee 変更しますた！心が折れるレベルのマサカリレビューをお願いします（嘘です。マサカリは持ち込み禁止です）

**Comment by amacbee** [comment]
良いと思います :)

**Comment by mahya8585** [comment]
![20090311_536373](https://cloud.githubusercontent.com/assets/10239748/6072795/2f976d08-ade9-11e4-8a01-c36036257a14.jpg)

ではこちらで横展開をおこない（ただのコピー）、
connpassリリースしてしまいます！

本issueのゴール：3日分の作業日connpassリリース完了及びslack通知完了

**Comment by mahya8585** [comment]
http://pyladies-tokyo.connpass.com/event/11776/

先行して２月２１日分公開＆slack通知済み

**Comment by mahya8585** [comment]
- http://pyladies-tokyo.connpass.com/event/11828/
- http://pyladies-tokyo.connpass.com/event/11859/

３日分全てのconnpass作成完了、slack通知済み。
本チケットゴール達成によりクローズします。
