### ISSUE TITLE
当日スタッフ公募用のconnpassイベントを作成する

### ISSUE THREAD

**Issue by amacbee** [PyLadiesTokyo/girls-tech-fes#21]
当日スタッフの公募をconnpassで行う形にしたいと思います．
以下の内容を記載する必要があるはず（現時点で思いつく限り）
- 少なくとも前日の作業日には来て欲しい ref. #20
- 午前／午後両方手伝えるのか #8 
- （当日のスタッフ分担のアンケートも入れてみる？ ref. #19 ）

**Comment by mahya8585** [comment]
うっかり先に作業日connpassを作成してしまった・・・
上記内容に合わせてconnpass 作成を行う。

ゴール：connpassイベントの公開及び既存スタッフへの周知と登録依頼まで行うこと
