### ISSUE TITLE
東大広報/Anita Borgへの質問

### ISSUE THREAD

**Issue by nobolis** [PyLadiesTokyo/girls-tech-fes#24]
- 東大広報/Anita Borgへの質問事項があったらこちらのコメント欄に投げてください。
- 永合氏（東大広報）・川久保氏（Anita Borg）に@nobolisが連絡します。
- #+issue番号でissueにリンクが張れます

**Comment by nobolis** [comment]
- 質問事項 in #5  
  2015/02/03 本日対応予定（延期）  
  2015/02/06 質問事項詳細確認中→確認完了 
  2015/02/07 質問連絡完了（ネットワーク環境とSSH利用可否について）

**Comment by amacbee** [comment]
> @nobolis さんには当日の時間的な話 (いつから入れていつまでに場所を開放する必要があるのか) や具体的な場所の話 (教室どこ使えるのか) などの話を東大側とつめる作業をして頂きたい感じ(ΦωΦ)

**Comment by nobolis** [comment]
#55 開催教室情報確認
2015/02/18 連絡済
2015/02/21 確認・報告済

**Comment by nobolis** [comment]
#58 受付で必要なもの

**Comment by nobolis** [comment]
@amacbee りょうかいですノ当日の時間的なこと、教室、使える設備などつめていきます。

**Comment by uni-q** [comment]
@nobolis 
受付担当からの質問です〜 #58 

受付用に
長机1個（長机1個ぶんの広さがあれば、どんな机でも大丈夫）と椅子1〜2つ、それらがおけるスペースが欲しいです。
↓こんな感じ
![b9ebdgxceaaqxnr](https://cloud.githubusercontent.com/assets/1001133/6281028/28658f16-b8fb-11e4-98ee-fcdc5079491e.png)
- 長机1つ椅子2つを借りたいです
- 受付を設置するスペースを、教室入り口近くの教室内か外に置きたい
  - スペースはありますか？間取り図があったら見せて欲しいです。
  - 「廊下には置かないで欲しい、机は動かさないで欲しい」といった建物についての注意事項を教えて欲しいです。

以上です、よろしくお願いいたします

**Comment by nobolis** [comment]
@uni-q 了解しましたー。上記確認してみます。写真おもしろい。。。

**Comment by amacbee** [comment]
ref. #67

**Comment by nobolis** [comment]
@uni-q 
#58
部屋の広さはまだわからないですが、場所は
工学部2号館　1F　211号室
http://www2.mech.t.u-tokyo.ac.jp/access/campusmap/access01.html
平面教室、机・椅子固定だそうです。

**Comment by amacbee** [comment]
東大側にポスターを貼ってもよいか確認して下さい (ref. #71 )

**Comment by nobolis** [comment]
#58
#67 
#71 
東大に質問投げました！

**Comment by nobolis** [comment]
#74 当日の「全体集合」は代表者のみ出席か、全員出席か。

**Comment by nobolis** [comment]
@uni-q #58 
受付用のテーブルですが、可動式のものがないそうです。
教室の後ろの方を受付につかってください、椅子は動きます、とのことです。
教室の様子については地図と写真をドライブにアップしておきましたのでご参照くださいませ。
（構内地図と写真フォルダを作ってその中に入れてあります）

**Comment by uni-q** [comment]
なるほど、長机は借りられないのですね。
椅子に座って、机なしで受付しますね。

**Comment by nobolis** [comment]
@uni-q 教室の一番後ろの机じゃだめな感じでしょうか？

**Comment by uni-q** [comment]
@nobolis 
- 教室に入ってくる人が通りかかるような位置に固定机があったら、それを使う
- 教室に入ってくる人が通りかかるような位置に固定机がなかったら、椅子に座って行う

![2015-03-24 12 18 36](https://cloud.githubusercontent.com/assets/1001133/6795205/273c38e0-d220-11e4-9c6d-ded32a27d7f3.jpg)

↑こんな感じかなーと思いますが、、
まあ、前日準備のときに、実際のレイアウトを見て決めようと思ってます。

とりあえず、
机なしでも机ありでも受付できるように、道具を準備しとく感じで！

**Comment by nobolis** [comment]
@uni-q もしや教室の写真って見られてないですか？私がちゃんとシェアできていないかも？
Girls Tech Fes > 構内地図と写真フォルダに会場の写真を入れてあって、それによると出入り口は発表者の真正面あたりのようなのです。

**Comment by nobolis** [comment]
@uni-q 机なしだとしんどいかなと思うので、入り口と机の位置が遠すぎる～というようでしたら、なにか作業台的なものが借りられないか交渉してみますので、どうぞお申し付けを！
