### ISSUE TITLE
東大広報/Anita Borgからの質問・コメント

### ISSUE THREAD

**Issue by nobolis** [PyLadiesTokyo/girls-tech-fes#25]
- 東大広報/Anita Borgから質問事項があったらこちらのコメント欄に投げます。
- 特定のissueに関連する場合はissueにリンクを張ります。
- ご指名投稿することになると思いますので、ご指名のあった方は回答をコメント欄に書き加えてください。
- どうぞご協力よろしくお願いいたしますm(_ _)m

**Comment by nobolis** [comment]
[Done]　#27 大判ポスター用ワークショップの紹介文作成

**Comment by nobolis** [comment]
[Done]　#28 Girl Tech Fes HPからのリンク先について

**Comment by nobolis** [comment]
[Done]　#29 当日のタイムテーブル連絡

**Comment by nobolis** [comment]
[Done]　#31 ワークショップで使用するWindows PCへの事前準備

**Comment by nobolis** [comment]
#66 イベントタイトル変更提案への対応

**Comment by amacbee** [comment]
@nobolis 直筆署名の項目等があるので，東大への同意書等は当日渡す感じでも良いかを確認していただきたいですmm

**Comment by nobolis** [comment]
@amacbee 「同意していただけるのであれば、当日お持ち下さい」との連絡をもらっているので、当日渡しでOKです

**Comment by amacbee** [comment]
了解です！
