### ISSUE TITLE
大判ポスター用ワークショップの紹介文（100-200文字程度）作成

### ISSUE THREAD

**Issue by nobolis** [PyLadiesTokyo/girls-tech-fes#27]
Anita Borgより依頼がありました。
提出期限は現在のところ未定。
要担当決め。

**Comment by nobolis** [comment]
提出は2月中を目処にとのこと。

**Comment by nobolis** [comment]
ポスターだけでなくWEBページにも企画概要を記載予定。
提出され次第掲載するので、早めに提出してもらえると助かるとのこと。
最終提出ラインは2月。

**Comment by nobolis** [comment]
#3 へコメントdone

**Comment by amacbee** [comment]
100〜200字概要私が作成します〜（今日のお昼ごろ作業しますmm）
簡単な団体紹介と企画内容の紹介みたいな感じですよね？書いたらレビューお願いします @all

**Comment by nobolis** [comment]
それではよろしくお願いします！
簡単な団体紹介と企画内容でよいと思います。

**Comment by amacbee** [comment]
```
PyLadies Tokyoは，プログラミング言語Pythonが好きな女性のための団体です．
本イベントでは，「Pythonを使ってチャット機能を作ってみよう」というテーマのワークショップを行います．
"プログラミング"ってよく分からないけど興味ある！という方向けに，プログラミングの楽しさを体験して頂ける内容になっています．
少しでも興味を持って頂けましたら，どうぞお気軽にご参加下さい．
```

**Comment by amacbee** [comment]
内容がつながってないな．こっちのほうが良いか．

```
PyLadiesは，プログラミング言語Pythonが好きな女性のための国際的団体です．
本イベントでは，PyLadies Tokyoのメンバーで「Pythonを使ってチャット機能を作ってみよう」というテーマのワークショップを行います．
"プログラミング"ってよく分からないけど興味ある！という方向けに，プログラミングの楽しさを体験して頂ける内容になっています．
どうぞお気軽にご参加下さい．
```

**Comment by mahya8585** [comment]
![fyi](https://cloud.githubusercontent.com/assets/10239748/6121197/f65d2e06-b121-11e4-96b2-145b319f200a.gif)

文字数制限があると思うので調整の必要があるかとはおもいますが。。。一応れびゅ。

> 国際的団体
> 国際的なコミュニティとかでもいいかも？

カンマ＆ピリオドって学会式でいいかなと思うんですが、一般掲示向きではないかも・・・？
工学系の広報の温度感聞きたいかんじ

> プログラミングの楽しさを体験して頂ける内容になっています．

〜頂ける内容です
と言い切って良いかと思います。

**Comment by nobolis** [comment]
本体イベントのサイトが参考になるかも。
http://tuk.t.u-tokyo.ac.jp/schejule/te/contents/

**Comment by nobolis** [comment]
個人的には3文目以降は2文目の内容をもうすこし具体的に記述するような内容の方が実際にやることを想像しやすくなっていいかな（たとえば「xxxというツールを使ってコードを書いたり変更したりしながらどのようにチャット機能が変化するかを体験できます」とか）と思ったのですが、本体イベントも @amacbee さん的な文章なので、この線でよさそうですかねー。

@mahya8585 
カンマ&ピリオドは広報さんに他の文章と同じ体裁に揃えてもらえるようお願いしましょうか。

**Comment by amacbee** [comment]
@mahya8585 カンマ＆ピリオドは私の癖なんですが，言われてみれば違和感ある＼(^o^)／w
今の文章でいちおう200字ギリギリなんですが，国際的コミュニティでいきましょう．
@nobolis プログラミングの知識とか全然いらないよ！的な部分を全力で押したいので，具体的な単語とかない方が相手がひるまなくて良いかな〜というのを意識してみました！イベント中はある程度どういう技術を使うのか名前くらいは出す予定です〜

```
PyLadiesは、プログラミング言語Pythonが好きな女性のための国際的コミュニティです。
本イベントでは、PyLadies Tokyoのメンバーで「Pythonを使ってチャット機能を作ってみよう」というテーマのワークショップを行います。
“プログラミング”ってよく分からないけど興味ある！という方向けに、プログラミングの楽しさを体験して頂ける内容になっています。
どうぞお気軽にご参加下さい。
```

**Comment by nobolis** [comment]
とりあえず、上記文章で確定ということでいいですかね。
他にご意見がある方もいるかもしれないので、とりあえず提出はペンディングして、2月12日に提出しようかと思います。

**Comment by amacbee** [comment]
@nobolis 問題なかったら確定してさくさく提出してしまって良いですよ〜

**Comment by nobolis** [comment]
@amacbee そうですか？じゃあ提出しちゃいますね。

**Comment by amacbee** [comment]
はい！お待たせするのもあれなので．
よろしくお願いします〜

**Comment by nobolis** [comment]
おくりましたー。
