### ISSUE TITLE
Girls Tech Fes HP上での団体紹介ページリンク先について確認

### ISSUE THREAD

**Issue by nobolis** [PyLadiesTokyo/girls-tech-fes#28]
Girls Tech Fes HP（ http://www.t.u-tokyo.ac.jp/epage/event/2015/150128_1.html）
における団体紹介ページリンク先について

上記イベント案内からのリンク先は
PyLadies Tokyo
http://pyladies-tokyo.connpass.com/

および、作られる予定のconnpassイベント応募サイトでよいでしょうか？

**Comment by amacbee** [comment]
はい，そのようにお願いしますmm

**Comment by nobolis** [comment]
了解しましたー。
