### ISSUE TITLE
事前予約（募集）ページの作成

### ISSUE THREAD

**Issue by mahya8585** [PyLadiesTokyo/girls-tech-fes#3]
PCの台数に限りがあるため、事前に参加の募集を立てるようにする。
２月前半までにconnpassにイベント立てる。
- タイピングができる人（高校・大学生向け）

担当者対象：connpassオーナー

ゴール：connpassページを作成し、girls-tech-fes本部にURL送付を行う。

**Comment by mahya8585** [comment]
- アンケートで参加者レベルを確認
- PCはこっちで準備している旨を記載

**Comment by nobolis** [comment]
* あるいはある程度参加者レベルを明記しても

**Comment by nobolis** [comment]
すみません、間違えてクローズしたらしい

**Comment by nobolis** [comment]
リオープンできました。ごめんなさい。

**Comment by amacbee** [comment]
現時点で見た範囲でコメントします〜
- Python Workshop -> プログラミング体験イベント がいいかもしれません
- PyLadies Tokyoって？みたいな項も欲しい
- 内容は直前に変わる可能性もあるので（ないと信じたいですが・・・）具体的にどういうフレームワークを使うかみたいな項は入れない方向でお願いしますmm (プログラミング言語の一つであるPythonを使って，簡単なチャット機能を作ります，程度の範囲で)
- 当日の講師は私以外でもやりたい方いればどうぞって感じの温度感なんですがどうしましょうかね。。。とりあえずissueたてて決めますmm

**Comment by nobolis** [comment]
東大/Anita Borgより、企画概要紹介（ウェブサイト・ポスター掲載用、100～200字）を早めに作成してほしいとの依頼が来ています #27 

事前予約ページの情報と内容がかぶると思うので、事前予約ページ担当者に作成してもらうのが妥当かなと思いますが、お忙しいでしょうか？

むずかしければ、募集ページ掲載予定の情報を教えてもらって@nobolisが作成します。
こちらは余裕があるので、面倒だったら投げてもらってOKですよ。

**Comment by nobolis** [comment]
企画概要文作成は@amacbee 担当ということで、了解いたしました。

**Comment by amacbee** [comment]
http://pyladies-tokyo.connpass.com/event/11662/
