### ISSUE TITLE
当日のタイムテーブル確定

### ISSUE THREAD

**Issue by nobolis** [PyLadiesTokyo/girls-tech-fes#30]
先方より当日のタイムテーブルを連絡してくださいとのリクエスト#29 がありました。

打ち合わせ#1より、
当日タイムスケジュール：
11:00〜12:00　１回目　ワークショップ
12:00〜14:00　ランチ＆コミュニケーションタイム＆次回準備
14:00〜15:00　２回目　ワークショップ
15:00〜16:00　コミュニケーションタイム＆片付け

となっていますが、このスケジュールで確定でしょうか？

**Comment by mahya8585** [comment]
上記スケジュールで相違ないです！
( @amacbee 今後変更の可能性があるようであれば示唆ください）

**Comment by amacbee** [comment]
問題ありません！上記の通リでよろしくお願いしますmm

**Comment by nobolis** [comment]
了解しました－。上記スケジュールを東大/Anita Borgに連絡しておきます。
