### ISSUE TITLE
ワークショップで使用するPCへの事前準備が必要か否か

### ISSUE THREAD

**Issue by nobolis** [PyLadiesTokyo/girls-tech-fes#31]
@amacbee 
ワークショップで使用するPCへの事前準備が必要でしたらお知らせください。

**Comment by amacbee** [comment]
可能であれば事前にPCへ
- エディタの導入
- Python環境の導入
- ワークショップに利用するコードをダウンロード

などやりたいです．
恐らく東大側でこれらを対応するのは難しいと思うので，前日にこの事前準備の時間を頂けるか聞いて頂きたいです〜

**Comment by nobolis** [comment]
上記の項目について事前導入が必要ということで了解です。
以下確認です:
- 前日希望とのことですが、当日朝よりは前日がいいですか？
- 準備時間は何時間くらいかかりそうですか？（作業人数次第かもしれませんが、目安として教えてください）

**Comment by amacbee** [comment]
もし環境導入に何らかの問題があった場合，前日であればまだ対応出来ることもありそう（かつ当日朝はバタバタしてそう）なので，当日朝よりは前日が良いです．
逆に作業時間として何時間頂けるか聞いてみて欲しいのですが（流石に厳しいとは思いますが可能であればあるだけ欲しい），Python＆環境の導入×25台と見て少なくても2時間は必要かなと思います．
無理な場合は代替案を考えるので，早めにご連絡頂けると嬉しいです．

**Comment by nobolis** [comment]
前日希望で了解です。
時間はできるだけ長い方がよいということで、希望を出してみますね。

**Comment by nobolis** [comment]
必要な作業について連絡しました。

**Comment by amacbee** [comment]
ありがとうございます！

**Comment by nobolis** [comment]
事前準備の詳細 --> #38
