### ISSUE TITLE
イベントについてTwitterやFacebook等SNSで発信する

### ISSUE THREAD

**Issue by amacbee** [PyLadiesTokyo/girls-tech-fes#33]
アカウントの管理者権限持ってる人じゃないのと無理なので，持ってる人の中で割り当てたい

**Comment by saorio** [comment]
これって、普通につぶやいたり、投稿するのでは意味ないんですか？管理者でないといけない理由が知りたいです。

**Comment by amacbee** [comment]
あ，説明が足りませんでしたすみません。。。
PyLadies Tokyoの公式アカウントとしてつぶやいたり投稿したりする事を考えています．
普通につぶやいたり投稿するのも大歓迎です！

**Comment by mahya8585** [comment]
各自アカウントでの拡散は是非現メンバーみなさんにお願いするとして←
公式Twitter/FBやりますよ〜
FBはconnpassページ作成完了後と一週間前・前日
Twitterは週一ぐらいでつぶやいておきますかね・・・

スタッフ公募も含めて拡散しませう（スタッフ公募ペー時作成完了後まとめてお知らせ出します）
こちらは2月の作業日までに１回にとどめておくかんじで・・・いいかな。。

**Comment by amacbee** [comment]
お願いします！上記の感じで問題無いですmm

**Comment by mahya8585** [comment]
╭( ・ㅂ・)و ̑̑

**Comment by mahya8585** [comment]
facebook第一弾配布だん
Twitter第一弾配布だん

**Comment by mahya8585** [comment]
Facebook / Twitter 共に　ワークショップ参加者向けのconnpassアナウンスだん。
直前アナウンスや前日アナウンス・開催レポなどの広報活動については別途issueで対応するものとし、
本issueは完了とします。

**Comment by saorio** [comment]
Facebookで早速シェアしました！

2015年2月17日火曜日、maaya ishidanotifications@github.comさんは書きました:

> Closed #33 https://github.com/PyLadiesTokyo/girls-tech-fes/issues/33.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/PyLadiesTokyo/girls-tech-fes/issues/33#event-236941876
> .

## 

太田 沙織
mail:saori.oota3@gmail.com
tel:080-1296-0494
