### ISSUE TITLE
東大/Anita Borgへ画像素材提供

### ISSUE THREAD

**Issue by nobolis** [PyLadiesTokyo/girls-tech-fes#37]
@all
東大/ABより、
「ポスター、WEBには、ロゴも使わせていただく予定です。
その他、使ってもいい魅力的な画像などあれば共有頂けるとうれしいです。」
とのことですので、素材をお持ちの方がいらっしゃいましたらご提供頂けるとうれしいです。

**Comment by amacbee** [comment]
あまり写真がないんですがとりあえず。。。
https://www.facebook.com/PyLadiesTokyo/photos_stream

**Comment by nobolis** [comment]
@amacbee
情報ありがとうございます。
こちらのURL連絡しておきますねーノ

**Comment by amacbee** [comment]
私はイベント中写真を撮っていない (=いつも忘れている) のですが，恐らく他の方は私よりも写真を持っているので，Slackの @channel 等を利用して聞いてみて下さい〜

**Comment by nobolis** [comment]
なるほど、@channelに投げてみるといいんですね。やってみます✋

**Comment by amacbee** [comment]
:star:
