### ISSUE TITLE
ワークショップで使用するPCへの事前準備

### ISSUE THREAD

**Issue by nobolis** [PyLadiesTokyo/girls-tech-fes#38]
@amacbee 
3月27日（金）からPC利用可能、27日（金）と28日（土）午後であれば作業可能（要調整）とのことです。
PCのOSはWindows7、無線LANカード、マウス付き。

日程希望は3月28日（土）午後でよかったでしょうか？
SSHは全部接続できる必要がありますか？
接続に関する資料はクローズドでアップします。

**Comment by amacbee** [comment]
日程希望は3月28日でお願いします．
SSHは可能であれば全台接続出来ると嬉しいです．

**Comment by nobolis** [comment]
了解です！そのように連絡しておきますねー

**Comment by amacbee** [comment]
お願いします〜

**Comment by amacbee** [comment]
前日の午後であれば作業可能との事なので，当日東大に出向いて作業

**Comment by amacbee** [comment]
ref. #46 
ref. #48 
ref. #51
