### ISSUE TITLE
各担当の決定

### ISSUE THREAD

**Issue by mahya8585** [PyLadiesTokyo/girls-tech-fes#4]
【決めておきたいstuff 役割】
- girls-tech-fes / annita borg との事前協議・調整  @amacbee @nobolis 
- サポートメンバーの管理 @mahya8585
  - まずはメンバーのスキルチェックアンケート作成
  - 湧いたタスクをスキル（もしくはやってみたいこと）に応じてissueの割り振り
- コンテンツ作成準備 
  - webアプリ作成   @amacbee  @sinamon129 @sayadroid 
  - 当日作業マニュアルをリバース書き起こし @mahya8585
  - 実作業レビュー @all
- connpass作成や広報 @mahya8585 @mamimumemo
- 当日の運営準備細かいもの
  - 名簿作成  -> connpassから自動で出てくる
  - スタッフ名札 @mamimumemo
  - 参加者名札 @mamimumemo
- Tシャツ作成  @uni-q 

★当日役割
- 受付
- 講師 / 進行
- 講師補佐
- タイムキーピング / 広報

**Comment by saorio** [comment]
質問です。当日、講師役の方以外に適宜PC周りで困ったことがあった場合の質問受ける人が２〜３人いた方が良いかなと思うのですが、、いかがでしょうか。

**Comment by mahya8585** [comment]
@saorio 講師補佐として追加しました

**Comment by saorio** [comment]
！お役にたてるか不安ですが。。

**Comment by uni-q** [comment]
ワークショップって、サポートの方、何人かいますよね。
参加者5人につき、1人サポート付いてたら十分。
参加者10人にサポート1人がギリギリな感じかな？（ただのイメージ）

**Comment by nobolis** [comment]
サポートは必要ですよね。
確認ですが、当日スタッフは基本的に今手を上げているメンバーのみになりそうですか？
それとももう少し増える予定でしょうか？

**Comment by amacbee** [comment]
PyLadies Tokyo Meetupにこれまで参加されていた方で， #engineering-envet にjoinしている方は，サポートをやりたいとおっしゃっていた方たちです．でも，こちらもはっきりしていないので，これからスタッフ名簿を作成する際に，もう一度全員に聞いてみますmm

**Comment by nobolis** [comment]
現状14名ですね。

**Comment by mahya8585** [comment]
【メモ】
当日担当割り振りは2月21日に決定する

**Comment by amacbee** [comment]
これからもう一度PyLadies Tokyoのconnpassグループに入っている方に向けて，スタッフ募集メールを投げてみようかな

**Comment by mahya8585** [comment]
Googleに同様の一覧作成済み。
connpassグループメンバーへのメール配信済み。（１回失敗して訂正文投げた。。。
