### ISSUE TITLE
チャットへの投稿メッセージにユーザ名をつける

### ISSUE THREAD

**Issue by amacbee** [PyLadiesTokyo/girls-tech-fes#44]
よろしくお願いします！！！←

**Comment by mahya8585** [comment]
デモソースのnot websocket版チャットが本件実現しているので、こちらを参考に進めようと画策中だったが。。。

not websocket版はgoogleの認証システムを使いログイン＋ユーザ名の表示を行っている。
googleのアカウントないと実現できない。
持ってない子がいそうなので、別の方法を考える。

それにしても同じチャット昨日でもjsの組み方とかdefの構成の仕方とかが結構異なった作りになってて、読んでいて勉強になる。

**Comment by mahya8585** [comment]
ページ遷移の仕組みとかformの受け渡しを理解しはじめた。テンションあがってきた。

**Comment by mahya8585** [comment]
できた・・・・！

**Comment by amacbee** [comment]
:star:
