### ISSUE TITLE
前日のWindowsセットアップ手順の整理

### ISSUE THREAD

**Issue by amacbee** [PyLadiesTokyo/girls-tech-fes#46]
私がやります

**Comment by amacbee** [comment]
- Desktopに `girls-tech-fes` という作業用ディレクトリをコピー (作業用ディレクトリを予め用意) ref. #48
- Windows 環境に以下をインストール
  - Python (2.7.9): https://www.python.org/downloads/
  - PyCharm: https://www.jetbrains.com/pycharm/
- PyCharmにて `girls-tech-fes` のvirtualenvを作成 (保存先は各々のhomeディレクトリ以下に `virtualenvs` 的なディレクトリ作る)
- `girls-tech-fes` というプロジェクトを作成し，作業用ディレクトリを指定する
- 使用するインタプリタに `tornado` を導入する (pip)

**Comment by amacbee** [comment]
さくっと書いておくとこういう感じ？

**Comment by amacbee** [comment]
ref. #51

**Comment by amacbee** [comment]
ref. #38

**Comment by amacbee** [comment]
ref. #56

**Comment by nobolis** [comment]
PyCharmでTornadoのパッケージを検索するといろいろと出てくるのですが、どれをインストールしたらよいのでしょう?

**Comment by nobolis** [comment]
とりあえずただの"tornado"をインストールしてみました

**Comment by nobolis** [comment]
Girls Tech Fes用Windows PCセットアップ手順を試してみた（はじめてのPyCharm !）ので、そのときの作業の覚え書きをDocとしてアップロードしておきましたノ
間違っているところなどありましたらご指摘お願いします！

**Comment by amacbee** [comment]
ありがとうございます！後ほど確認します〜

**Comment by saorio** [comment]
@nobolis Docってgoogle documentに無かったのですが、どちらでしょう、、？ちょっと会社のPCがWinなので試したいです。

**Comment by nobolis** [comment]
@saorio Girls Tech Fesドライブに「Girls Tech Fes用Windows PCセットアップ手順を試してみた」っていうDocを入れたんですが、シェアされてないかんじですか？私の共有設定が間違っているかんじですかね？

**Comment by saorio** [comment]
発見できました！
ありがとうございました^ ^
やってみます。

2015年3月2日月曜日、Katayanagi, Nobukonotifications@github.comさんは書きました:

> @saorio https://github.com/saorio Girls Tech Fesドライブに「Girls Tech
> Fes用Windows
> PCセットアップ手順を試してみた」っていうDocを入れたんですが、シェアされてないかんじですか？私の共有設定が間違っているかんじですかね？
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/PyLadiesTokyo/girls-tech-fes/issues/46#issuecomment-76657284
> .

## 

太田 沙織
mail:saori.oota3@gmail.com
tel:080-1296-0494

**Comment by nobolis** [comment]
よかったです(^^)
気づいたことがあったら適宜加筆・修正よろしくお願いいたしますm(_ _)m
