### ISSUE TITLE
午前と午後の入れ替わりの際にローカル＆サーバの環境を戻す手順を整理する

### ISSUE THREAD

**Issue by amacbee** [PyLadiesTokyo/girls-tech-fes#49]

**Comment by amacbee** [comment]
- 削除作業
  - 前の人が利用したリポジトリ
  - PyCharmのプロジェクト
- 初期状態のリポジトリをコピー
- 新しくPyCharmのプロジェクト作成
- WebSocketデモの動作確認
- 起動した状態で待機

**Comment by mahya8585** [comment]
```
削除作業
前の人が利用したリポジトリ
PyCharmのプロジェクト
初期状態のリポジトリをコピー
新しくPyCharmのプロジェクト作成
```
- 前日の作業でプロジェクトを2つ用意し、PCに配置しておく
  - 午前用プロジェクト
  - 午後用プロジェクト
- 午前ワークショップ終了後、PyCharmで開くプロジェクトの差し替えを行う
