### ISSUE TITLE
当日必要なものリスト

### ISSUE THREAD

**Issue by mahya8585** [PyLadiesTokyo/girls-tech-fes#5]
- 【Done】Winマシン 25台（ユーザ利用20台　メンバー用５台）
  - winで動くコンテンツ環境作成
- 教室１部屋
  - プロジェクターがあるか確認
  - マイクがあるか確認 
  - ssh空いてるか確認
  - そもそもネット環境どうなの確認
- 当日予約管理用スプレッドシート

**Comment by uni-q** [comment]
- Tシャツ？
- 先生用の名札とか？
- 受付用の名簿？とかパソコン（connpassで受付管理するよう）

**Comment by nobolis** [comment]
- ポインタ？（必要なら持って行きます）

**Comment by uni-q** [comment]
まずは担当を決めてから、担当者が中心になって「当日の必要なものリスト」を洗い出した方が良さそうな。
受付や講師など、担当によっての必要なものがあるので。

**Comment by nobolis** [comment]
@mahya8585 確認事項の確認です：
- そもそもネット環境どうなの確認
  これは25台のPCをネット接続できる環境があるかどうかを確認すればよいですかね？

*　ssh空いてるか確認
   SSHを利用して外部への接続が可能かどうか確認するということでしょうか？
　 詳しくないのでもう少し詳しく確認したいことの内容を教えて頂けると助かりますmm

**Comment by mahya8585** [comment]
@nobolis 

> そもそもネット環境どうなの確認 これは25台のPCをネット接続できる環境があるかどうかを確認すればよいですかね？

相違ないです！wi-fiでもランでも構わないですが、PC25台（スタッフが使用するものを含めると30台くらい？）を接続できるネット環境って大学側で用意してもらえるのか（すでに学校にあるよね）？
ということを確かめたい、というメモでした。

> ssh空いてるか確認 SSHを利用して外部への接続が可能かどうか確認するということでしょうか？

こちらも概ねご認識のとおりです！
SSHポートを利用して外部ネットワークへ接続し、ワークショップの運営をしたいと考えています。
そこで、先方に確認したい内容としては
- 大学側で用意いただいたネット環境で、SSHポートの利用ができるのか
- SSHポート利用に際し、 IP制限など制約事項があれば大学側から指示いただきたい
  - IP制限がかかっている場合はワークショップ用の接続先IPを事前開示することで当日までに設定しておいてもらうことは可能か

というあたりの確認になります。
ただし、現在ワークショップ用のアプリケーションの設計や実装が進んでいる最中のため、SSHポートの質問については今すぐ、ではなくもう少しPyLadiesが実際にワークショップする内容が形になってきてから質問を投げた方が良いかと思います。
（このあたりのネットワーク関連については形になってきてから質問事項や調整事項が増えそうなため）

次回作業日の各タスクの整理が終わってからで良いかもしれませんね！

@amacbee @sinamon129 その他環境周り質問事項の忘れ物があれば補足教示ください。

**Comment by nobolis** [comment]
@mahya8585 @amacbee @sinamon129 
- ネット環境の件
  PC30台分接続できる環境があるか確認ということで了解です。  
  最近はどうかわかりませんが、大学ってどこでもネット接続できるわけじゃないので（講義室で自由にWi-Fi使えたら学生授業聞かずに遊んじゃうかも？）、これは早めに聞いた方がよさそうですね。
- SSHの件
  　確認事項、理解できました！
  　SSHを利用できるか否かについては先に確認して、それ以外の詳細事項は次回作業日以降確認ということにしようかと思います。
- SSHが利用できなかった場合の代替案
  　もしSSHポートの利用ができないとなった場合は、どうしますか？
  　相手にこういう要望を出してほしい等のご意見ありましたら挙げてもらえると助かります。

**Comment by amacbee** [comment]
SSHポートは最悪講師だけ使えれば良い感じにするので（予定），なければないで問題ないです．
どちらにしろ個人の mobile wifi は念のため持ち込む予定なので！

**Comment by nobolis** [comment]
@amacbee 
SSH利用できるか否か確認、なければないでOKということで、了解いたしましたー。

**Comment by amacbee** [comment]
これ現時点でどうなってるんでしたっけ？

**Comment by uni-q** [comment]
「当日必要なもの」だと大きすぎるので、担当ごとに洗いだした方が、見落としがなくて良いような気がしますが、どうでしょうか？

当日の流れで適当に洗い出してみると…
- 受付で必要なもの ( #52 から派生した別チケットに集約したいかも？）
- 事前説明プレゼンで必要なもの（プロジェクター、マイク、プロジェクターとmacをつなげるコネクタ）
- ワークショップで必要なもの（ネットワークやPC、机、椅子、とか。このissueをワークショップで必要なものと変更してもいいかもしれません）
- ワークショップ終了後に必要なもの（アンケート用紙？）

**Comment by amacbee** [comment]
いいですね！
このissueを親issueとして子issueたてますmm

**Comment by nobolis** [comment]
#59 プレゼンで必要なものと#60 ワークショップで必要なものは内容がかぶる感じがしますね。
たとえばプロジェクタとマイクはプレゼンでもワークショップでも使用しますよね？

洗い出しは担当毎の方がよいと思いますが、当日必要なものはむしろワークシートにまとめて記入した方が、全体を一覧できてみんなで見落としが確認しやすく、かつ、持ち物チェックシートとしても使いやすいかなと思うのですが、いかがでしょう。

**Comment by uni-q** [comment]
そうですね。各担当で必要なものをリストアップしたら、全体をまとめて見比べるフェーズがあると、無駄ないですね。

**Comment by uni-q** [comment]
スプレットシート作りました。
https://docs.google.com/spreadsheets/d/1dtugWVZ5pBS_u20kF0qDvUlm2y0tOpCCowWE9cOvv1U/edit?usp=sharing
ここに各段階・担当で必要なものをひとまずリストアップしますか。

**Comment by nobolis** [comment]
さっそくありがとうございます(^ ^)

**Comment by saorio** [comment]
名札はスタッフと参加者の両方必要ないんじゃないかなと私も思いました。
それ以外は問題ないと思います。
また思いついたら記載します。

2015年2月18日水曜日、Katayanagi, Nobukonotifications@github.comさんは書きました:

> さっそくありがとうございます(^ ^)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/PyLadiesTokyo/girls-tech-fes/issues/5#issuecomment-74809566
> .

## 

太田 沙織
mail:saori.oota3@gmail.com
tel:080-1296-0494

**Comment by amacbee** [comment]
（大変遅くなりました・・・）ありがとうございます！
スプレッドシート記入しておきます(｀･ω･´)ゞ

**Comment by saorio** [comment]
ペンとか紙とか必要でしたら多めに持っていきます。

**Comment by nobolis** [comment]
@saorio ありがとうございます(^ ^)ノ念のためペンとか紙は用意しておいたほうがいいかもしれませんね。

**Comment by amacbee** [comment]
洗い出しは大体終了
