### ISSUE TITLE
2015/03/28 作業日にWindows PCのセットアップを行うメンバーの決定

### ISSUE THREAD

**Issue by amacbee** [PyLadiesTokyo/girls-tech-fes#51]
前日に東大 (本郷キャンパス) に出向いてPCのセットアップを行うメンバーを決定する
最低でも3人位は欲しいけど，他のタスクと要調整

**Comment by amacbee** [comment]
全員で本郷キャンパスに行くという手もあるけど未定

**Comment by saorio** [comment]
東大は家から近いのでできますよ！
やり方共有頂ければ^^;

2015年2月17日火曜日、Ai MAKABInotifications@github.comさんは書きました:

> 全員で本郷キャンパスに行くという手もあるけど未定
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/PyLadiesTokyo/girls-tech-fes/issues/51#issuecomment-74611877
> .

## 

太田 沙織
mail:saori.oota3@gmail.com
tel:080-1296-0494

**Comment by amacbee** [comment]
@saorio よろしくお願いします！

**Comment by amacbee** [comment]
ref. #38

**Comment by amacbee** [comment]
作業日には全員で東大に行くことにしたため，行けるメンバーでセットアップを行うことにする
