### ISSUE TITLE
当日の受付方法を決定する

### ISSUE THREAD

**Issue by amacbee** [PyLadiesTokyo/girls-tech-fes#52]

**Comment by amacbee** [comment]
受付担当を @uni-q さんにお願いしたい感じ

**Comment by uni-q** [comment]
:ok_hand:

**Comment by uni-q** [comment]
TODO あとでヒアリングしたり決めたりすること
- 受付に必要な人数
- 受付の方法（紙かPCか）
- 受付の場所
- 借りたいもの（長机、椅子、ホワイトボードなど）
- スタッフが入場〜準備できる時間
- 受付時間

※ 会場やイベント本部への質問は #24 へ

**Comment by uni-q** [comment]
- 受付に必要な人数：1〜2 人
- 受付の方法（紙かPCか）：PCで。（念のため紙も印刷しておく）
- 受付の場所：当日いって見てみる
- 借りたいもの（長机、椅子、ホワイトボードなど）：教室内のものしか借りられない。固定机のみ。椅子は動かして良い。
- スタッフが入場〜準備できる時間：前日準備のときに設営する
- 受付時間： https://docs.google.com/spreadsheets/d/1Qo1ekvYLxy6uWzRogHnVSjE-yZhVdJgcaBX5Fe9iDgA/edit#gid=437513407

**Comment by uni-q** [comment]
当日のスケジュール
https://docs.google.com/spreadsheets/d/1Qo1ekvYLxy6uWzRogHnVSjE-yZhVdJgcaBX5Fe9iDgA/edit#gid=437513407

入場の流れ
1. connpass で使用している名前を聞く、もしくは connpass 受付票を見せてもらって受付番号を確認
2. connpassの参加管理画面 http://connpass.com/event/11662/participants/ もしくは、印刷した申込者一覧にチェックを入れる。
3. 名札を渡す。

退場の流れ
1. 名札を返してもらう

**Comment by uni-q** [comment]
当日の受付の流れをここにまとめた
https://docs.google.com/document/d/1xfUv4Vq-yi9EFY4TBlTBOgVWGO2-ZG_hyW9Msi9c-2Q/edit?usp=sharing
