### ISSUE TITLE
当日のプレゼン資料を作成する

### ISSUE THREAD

**Issue by amacbee** [PyLadiesTokyo/girls-tech-fes#53]

**Comment by mahya8585** [comment]
座学説明（webscketってなに？とか全体のアーキテクチャの流れとか）は @amacbee 以外の人がやってもいいかもしれないですね。漫才的に進めてもいいと思うし。。。

**Comment by amacbee** [comment]
お願い出来るならお願いしたい感じです(ΦωΦ)
内容的にはWebSocketの説明とか全部省いて何重にもラッピングされたよく分からないけど何となく伝わったラインを目指すつもりでした

**Comment by amacbee** [comment]
- Pythonについての説明
- PyLadies Tokyoについての説明
- WebSocketという名前を使わずに，簡単なコンテンツの説明
  - appの全体的な動作の流れについても説明

**Comment by sayadroid** [comment]
【共有】

2015-02-27 12:00-
@amacbee と 私で認識すり合わせしました。

直前に完成形のキャプチャスライドなどを入れ込もうと思いますが、
土台となるスライドは３月中旬頃までには上げるようにします mm

**Comment by amacbee** [comment]
よろしくお願いします！

**Comment by sayadroid** [comment]
大変遅ればせながら、スライド第一稿です。
#67 にある諸注意などは、内容がわからなかったので差し込んでおりませんmm

https://drive.google.com/drive/u/1/#folders/0B9h8aVVbzBiCfnAwclNiT21iQmRMTnlSelZRSzRCRWpKWHRvb2pKQnItOXl5bzFQVFU0VlU/0Bz8Aig6dBzaKfnFrN2xjT1hOZ3ZRcE9DVGd2VUlBSjJtdUtDUnZZSDI3WE01Y3ZrU0ZLTkU

**Comment by amacbee** [comment]
Girls Tech Fesフォルダに上記スライドを移動しました！
遅くなりましたがこれから見ますmm

**Comment by amacbee** [comment]
Pythonの説明が専門用語が多い気がするので，こんな感じでどうでしょう？

```
- (ほとんどのプログラミング言語がそうなんですが) 無料で使える
- スッキリしていて読みやすい / 書きやすい
- 海外では初心者向け言語として初学者向けプログラミング授業などに取り入れられている
- 様々な用途で使える
    - Web掲示板を作ったり，データ分析を行ったり，Pepperを制御したり，etc.
```

**Comment by amacbee** [comment]
諸注意の話は，会場に関する連絡事項の話を指していたので，私の方で自己紹介スライドと一緒にまとめちゃいますmm

**Comment by nobolis** [comment]
かわいいスライドですねー。内容もわかりやすいと思いました。
  2点ほど、コメントです：
1. 順序について
   2ページ目にいきなりPythonistaっていう専門用語？が出てくると、　　  
   知らない人はぽかーんとしちゃうかなと感じました。  　　  

　たとえば6～8を先に回して、  
  プログラミングのこと  
→様々なプログラミング語があるよ
　→今日はそのうちのPythonやるよ（Pythonの説明）
  →PyLadiesはこのPythonが好きな人＝Pythonistaの集まりだよ  
  →世界中にPyLadiesがあるよ  

　っていう流れの方がすんなり頭に入るような気がしました。  
1. 活動内容について  
   　　もう少し簡潔でもいいのかなとも。  
   　　いつ立ち上がって、こういう頻度でこういう活動しています（、参加者募集中です）、とか。

**Comment by nobolis** [comment]
諸注意について、参加者に伝える必要があるのは飲食の件ですよね？  

基本参加者の会場内飲食は禁止（スタッフも講師以外はWorkshop中は飲食はしない）ようにした方がよいかと思うのですが、いかがでしょうか。

**Comment by amacbee** [comment]
飲食の件です．

> 基本参加者の会場内飲食は禁止（スタッフも講師以外はWorkshop中は飲食はしない）ようにした方がよいかと思うのですが、いかがでしょうか。

はい，私も会場内飲食はスタッフ / 参加者ともに飲食は厳禁の方向でいきたいと考えていますmm

**Comment by nobolis** [comment]
@amacbee 了解です(^ ^)ノ

**Comment by sayadroid** [comment]
@amacbee @nobolis 
確認、レビューありがとうございます! :)
週末までに修正します..!!

**Comment by sayadroid** [comment]
皆さんに頂いた意見を反映し、ver.2を格納しましたmm
ありがとうございます…！
https://drive.google.com/drive/u/1/#folders/0B9h8aVVbzBiCfng3Z3oxSjdHWC1WejJXQk0zVTEyLW5Fa3g3eVlHeHRqZlhvNFRET3ByVHM

**Comment by nobolis** [comment]
@sayadroid 修正ありがとうございます！これでよいと思います！
