### ISSUE TITLE
当日の流れを決定する

### ISSUE THREAD

**Issue by amacbee** [PyLadiesTokyo/girls-tech-fes#54]
よしなに他の人と連絡をとりつつ決定して欲しい感じ
当日の役割分担の話ともリンクするはず
- 何時にどこに集合するのか
- いつまでに教室に入れる？いつまでに教室をあける必要があるのか
- 午前と午後の入れ替わり作業の整理 (何時までに作業を始める必要があるとか終わる必要があるとか)
- その他諸々

**Comment by amacbee** [comment]
当日スタッフの割り振り ( ref. #19 ) とかとまとめてやって貰いたい感じ

**Comment by nobolis** [comment]
現状の予定はこんな感じとのことです：
- 8時半から会場が利用可能
- 9時にイベント全体で集合（ミーティング）

**Comment by nobolis** [comment]
全体集合の詳細がわかり次第報告しますね。
ref. #24 #74

**Comment by nobolis** [comment]
@saorio  東大とのミーティング時間は「全員参加」にして頂けますか？よろしくお願いします。
ref. #74
