### ISSUE TITLE
必要情報が集まりしだい事前募集ページに追記する

### ISSUE THREAD

**Issue by amacbee** [PyLadiesTokyo/girls-tech-fes#55]
とりあえず今思いつくのは以下くらい
- 当日ワークショップが行われる具体的な教室名
- ワークショップ資料へのリンク
- ( 他に何かしら担当する人がいるなら ) ワークショップ講師の追加

**Comment by nobolis** [comment]
教室名については質問投げておきました。
ref. #24

**Comment by nobolis** [comment]
開催場所情報は以下の通りです。更新よろしくおねがいいたします！

　〒113-8656　東京都文京区本郷7-3-1
　東京大学　工学部2号館　1F　211号室

**Comment by amacbee** [comment]
Done!
- 開催場所情報の変更
- イベントタイトルの変更

**Comment by amacbee** [comment]
必要な情報は追記済み
