### ISSUE TITLE
ワークショップ環境が正しく動作するか検証する（個人）

### ISSUE THREAD

**Issue by amacbee** [PyLadiesTokyo/girls-tech-fes#56]

**Comment by amacbee** [comment]
事前に用意した資料通りに操作することで，正しくワークショップ環境が構築できるかを検証する

**Comment by amacbee** [comment]
要：Windows環境（Pythonが入っていない環境であればなおよし）

**Comment by mahya8585** [comment]
#46 クローズに伴いクローズします。

**Comment by nobolis** [comment]
セットアップ手順は#46のもので完成という理解でいいですか？
自分のPCにPyCharmインストールしたいので、手順が決まっているならそれに従ってやってみようかなと。

**Comment by amacbee** [comment]
hai! ただ大雑把な説明なので分からなかったら聞いて下さいmm

**Comment by nobolis** [comment]
了解です。わからなかったら質問させていただきますノ
