### ISSUE TITLE
アンケート内容の決定

### ISSUE THREAD

**Issue by mahya8585** [PyLadiesTokyo/girls-tech-fes#6]
connpassで登録者宛に投げるアンケートの作成

子チケットで項目選定を行う

**Comment by mahya8585** [comment]
- PCの日常使用頻度（主にタイピング面）
- 年齢
- プログラミングしたことある人はその言語とレベル
- 初めての人はプログラミングに対するイメージの自由記述

その他何かあれば追記ください

**Comment by MamiSATO** [comment]
メールアドレスを教えて下さい。
（なにか連絡があった場合に使用します。）
　フリー記述

※PCのアドレス？携帯のアドレス？明記したほうがいいかも。

学年を教えてください。
　□高校1年生
　□高校2年生
　□高校3年生
　□高専1年生
　□高専2年生
　□高専3年生
　□高専4年生
　□大学1年生
　□大学1年生
　□大学1年生
　□大学1年生
　□その他

※チェックボックス形式？
※短大わける？
※大学院生もくる？

PCの使用頻度を教えてください。
　１週間に[XX]時間くらい使用する

PCの使用用途はなんですか？
　フリー記述

普段使用しているPCのOSを教えてください。
　□Windows
　□Mac
　□その他

プログラミングの経験はありますか？
　○ある
　○なし

プログラミング経験がある場合、経験言語を教えてください。
　フリー記述

プログラミング経験がある場合、レベルを教えてください。

プログラミング初経験の人は、プログラミングに対するイメージを教えてください。

**Comment by MamiSATO** [comment]
叩きを、googledocsに貼りました。
コメント編集お願いします！
https://docs.google.com/document/d/1eXkftP1DDgyy1Vc43Q122SUhD-DHHlsunHXl62qkYzA/edit?usp=sharing

**Comment by nobolis** [comment]
docがview onlyだった（connpassも権限なくて見られない）ので、こちらにコメントしますね。

メールアドレス、必要でしょうか？
あまり開示したがらない人もいるような気がするので、これがハードルになって断念する人も出てくるかなと。
書かせるとしても最後に、任意記入にした方がよいかなと思いました。

**Comment by saorio** [comment]
フリー記述だと書かない人もいるので、全部選択式にして、その他（）で書かせるとか。
集計する時もその方が楽かと思いますが、いかがでしょうか。。？
例えば、PCの使用用途については、□メール　□Web閲覧　□写真整理　□ゲーム　□その他（　）
複数選択式とかで、、、

**Comment by amacbee** [comment]
基本的に，アンケートは運営側で活かせそうな情報だけで問題ないと思うので，学年とかは大雑把に 大学生／高校生／高専生／その他 くらいで良さそうかなと思います．
使用頻度も恐らく適当に書いてくるだろうと思うので（実際に自分が聞かれても大雑把にしか書かない気がするので(___; ），PCの使用用途だけを聞いてみるだけで良いかもしれません．
プログラミング経験 (or 情報技術に関する知識) の欄はもう少し詳細に書きたい気がします．
- あなたの情報技術に関する知識について教えて下さい
  - PCの起動/終了方法は分かる
  - 高校や大学で情報技術に関する授業を受けたことがある
  - Microsoft Office (Word, Excel, PowerPoint 等) 製品を使ったことがある
  - ワープロ検定 等の情報技術に関連した資格を持っている
  - プログラミングがどういったことをするのか何となくイメージはある
  - 授業でプログラミングを行ったことがある
  - 自分で何かしらのコンテンツ（掲示板・HP 等）を作ったことがある

こんな感じ？
上記があれば，使用したことのある言語やレベル，イメージに関する質問はなくても大丈夫かなと思います．（完全に私のイメージベースですが・・・）

この意見には私も同意します．

> フリー記述だと書かない人もいるので、全部選択式にして

**Comment by nobolis** [comment]
メアドが必要な理由、理解しました。
https://pyladies-tokyo.slack.com/archives/engineering-event/p1423351547000003
https://pyladies-tokyo.slack.com/archives/engineering-event/p1423353008000006

フォローアップイベントも検討しているそうなので、メアドは本イベントおよび当該団体が企画するイベントに関する連絡事項の通知にのみ利用する旨を明記する必要があるかなと思います。

関連して、「フォローアップイベント等、関連イベントのご連絡に当該メールアドレスを利用させていただいてもよろしいでしょうか」といった質問を加えた方が親切かなと。

**Comment by amacbee** [comment]
フォローアップイベントのページ作成が間に合ったので，参加者へのフォローアップイベントの通知を現イベントと同時に行えそうです．なので，「フォローアップイベント等、関連イベントのご連絡に当該メールアドレスを利用させていただいてもよろしいでしょうか」はなくても大丈夫そう．
よろしくお願いします！

**Comment by mahya8585** [comment]
@amacbee @MamiSATO アンケートをconnpassに反映しました。
内容のレビューおねがいします

**Comment by amacbee** [comment]
http://pyladies-tokyo.connpass.com/event/11662/
