### ISSUE TITLE
ワークショップで必要なものを整理する

### ISSUE THREAD

**Issue by amacbee** [PyLadiesTokyo/girls-tech-fes#60]
よしなに以下のissueの内容をまとめて下さい
ref. #5 
- ネットワークやPC
- 机、椅子
- etc.

**Comment by nobolis** [comment]
とりあえず思いつくものをメモ:
- 参加者用PC (Windows7、無線LANカード、マウス付きが利用可能 #38 )  
- 電源タップ（あるいは電源設備があるか要確認 #24）
- ネットワーク（接続可、SSHについてはクローズドで資料をアップ済み）
- 机と椅子（教室が机椅子可動タイプか否か問い合わせ中 #24)
- プロジェクタ（チャット画面投影用、利用可能か問い合わせ中#24）
- マイク（利用可能か問い合わせ中#24）

**Comment by nobolis** [comment]
ワークシートに記入したのでクローズします
