### ISSUE TITLE
ワークショップ終了後に必要なものを整理する

### ISSUE THREAD

**Issue by amacbee** [PyLadiesTokyo/girls-tech-fes#61]
ref. #5 

あれば

**Comment by amacbee** [comment]
終了後アンケートとかあると良いのかもしれない

**Comment by mahya8585** [comment]
googleフォームとかでその場でサクッと答えられるように手配してみましょう

**Comment by amacbee** [comment]
作成したらレビューするのでAssigneeを私に変更して下さい！

**Comment by amacbee** [comment]
アンケートは当日に行う方が良さそう (紙でもWebでもどちらでも)

**Comment by mahya8585** [comment]
**全て任意項目とします**
- ワークショップ満足度(5段階ラジオボタン）
- 体感難易度(5段階ラジオボタン)
- 感想フリー(テキストボックス）
- Pythonに興味でましたか(3段階ラジオボタン）
- これからPython勉強してみたい（すでにやってる人はもっと深く勉強したい）と思いましたか(3段階ラジオボタン）
- connpass申し込み時のアカウント名（テキストボックス）

他に聞いとくことありますかね・・・

**Comment by amacbee** [comment]
ワークショップ満足度や感想の部分とまとめられる気がするので問題ないかな〜と思います

> Pythonに興味でましたか(3段階ラジオボタン）
> これからPython勉強してみたい（すでにやってる人はもっと深く勉強したい）と思いましたか(3段階ラジオボタン）

PyLadies Tokyoへの要望・質問の項目とあるといいかなと思います．
あと最後にPyLadies Tokyo Meetup 4への案内リンクも欲しいです．

**Comment by mahya8585** [comment]
OK作成します

**Comment by mahya8585** [comment]
http://goo.gl/forms/7ZYmTo4mjO

添削お願いします。

**Comment by uni-q** [comment]
ちょっと手をいれました。
LGTM

**Comment by amacbee** [comment]
![LGTM](http://www.lgtm.in/p/ke8OCitbq)
