### ISSUE TITLE
イベントタイトル変更の提案に対する対応

### ISSUE THREAD

**Issue by nobolis** [PyLadiesTokyo/girls-tech-fes#66]
Anita Borgからの担当さんより以下のご連絡頂きました。
対応についてご相談したいです。
「今回の貴団体のイベントタイトルですが、Pythonというキーワードは後ろに回して
はいかがでしょうか。
というのも、今回は対象がやや幅広く、Pythonをそもそも知らない方が多いかと思いますので、
チャットを全面に押し出した方がお客さんがひっかかるかと思った次第です。
例えば、、
「楽しいチャットを作ってみよう！〜Pythonを使ったプログラミング〜」
などいかがでしょう。宜しければ、ご検討下さいませ。」

**Comment by amacbee** [comment]
タイトル変更
「チャットを作ってみよう！〜Pythonでたのしくプログラミング〜」（イベントページの書き換え > ref. #55 ）

**Comment by nobolis** [comment]
タイトル変更投げましたので閉じます！
