### ISSUE TITLE
環境周りの質問

### ISSUE THREAD

**Issue by saorio** [PyLadiesTokyo/girls-tech-fes#67]
・PCにインストールしたpython,モジュールは消したりアンインストールが必要でしょうか？
・教室では飲食できないでしょうか？
・イベント用に準備用のお部屋は貸して頂けますか？そこでの飲食は良いでしょうか。
  #食堂とかあいているんでしょうか？外で調達する感じでしょうか。

**Comment by amacbee** [comment]
こちら再インストール等は必要ないはずです．ただローカルに学生が作成したプロジェクトをどこかに置いておく or 消す作業が必要なはずです

>  PCにインストールしたpython,モジュールは消したりアンインストールが必要でしょうか？

**Comment by nobolis** [comment]
質問ありがとうございます！
確認連絡しておきますー
#24

**Comment by saorio** [comment]
・windowsのアカウントでインストール権限があるものを頂けるかどうか。
それぞれのPCによって環境違うのかな？それだと変な動きするPCとかあったらやだな。。
・私たちのような主催側と、イベント参加者とは違うアカウントとか来れるんでしょうか。

**Comment by saorio** [comment]
大丈夫だと思うけど、PCにはどんなブラウザが入っているか、IEは１０以上であることを確認する。

**Comment by nobolis** [comment]
上記の質問すべて投げました－。#24

**Comment by nobolis** [comment]
教室利用関連についての回答をいただきました：
1）教室内の飲食は基本的にNGです（ペットボトル一人1本程度の持ち込みはOK）
2) 飲食は休憩室（スタッフ控室、ワークショップ会場の上の階の部屋）でお願いします。
3) 多量のゴミの廃棄は禁止とのことです。
以上、スケジュールワークシートに記載しておきました－。

**Comment by saorio** [comment]
了解です！
ありがとうございます。

2015年3月5日木曜日、Katayanagi, Nobukonotifications@github.comさんは書きました:

> 教室利用関連についての回答をいただきました：
> 1）教室内の飲食は基本的にNGです（ペットボトル一人1本程度の持ち込みはOK）
> 2) 飲食は休憩室（スタッフ控室、ワークショップ会場の上の階の部屋）でお願いします。
> 3) 多量のゴミの廃棄は禁止とのことです。
> 以上、スケジュールワークシートに記載しておきました－。
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/PyLadiesTokyo/girls-tech-fes/issues/67#issuecomment-77303480
> .

## 

太田 沙織
mail:saori.oota3@gmail.com
tel:080-1296-0494

**Comment by nobolis** [comment]
PC利用関連についての回答をいただきました：  
1. 管理者権限のあるアカウントでのログインは可能
2. PCの履歴は不明だが、（レンタル品であるため）レンタルにあたり、工場出荷状態に戻している
3. ウェブブラウザはアップデートされているが　バージョンは現段階では不明
4. インストールしたものは基本的にはアンインストールの必要はないが、翌日高校生の講座で使うので
　そこで問題にならない形にして戻して欲しい  

高校生の講座では「高校生が修学旅行等で行った道筋をTrackerでデータ蓄積しており、それをエクセルも活用して、加工してみる企画」のようです。

**Comment by amacbee** [comment]
参加者への注意事項 (e.g. 飲食NG) を事前スライドに載せる ref. #53
