### ISSUE TITLE
Python本体とPyCharmをUSBに入れる

### ISSUE THREAD

**Issue by amacbee** [PyLadiesTokyo/girls-tech-fes#68]
事前準備に必要なため．5本くらいあれば良いかな？
ref. #46

**Comment by mahya8585** [comment]
1本用意完了。動作確認のち複製を作成。。。

**Comment by mahya8585** [comment]
- PyCharm4.0.4インストーラ
- Python2.7.9インストーラ
- masterブランチソース（AM/PMの2セット）

3本USB作成済み。
本日事足りているか作業確認

**Comment by amacbee** [comment]
PCが工場出荷状態らしいので，Chromeも追加で入れたい

**Comment by mahya8585** [comment]
chrome入れました。
masterソースも一応入っていますが、この後ソースの最新化があると思いますので、
27日の夜に再度入れ直し（最新化）します。

**Comment by mahya8585** [comment]
アンケートフォームURLも入れておきました。
当日のショートカット作成しましょう
