### ISSUE TITLE
connpassに載せるためのdetail決定

### ISSUE THREAD

**Issue by mahya8585** [PyLadiesTokyo/girls-tech-fes#7]
- 開催時間と回数
  - 11:00〜12:00　１回目　ワークショップ
  - 12:00〜14:00　ランチ＆コミュニケーションタイム＆次回準備
  - 14:00〜15:00　２回目　ワークショップ
  - 15:00〜16:00　コミュニケーションタイム＆片付け
- １回のmax参加者人数
- 今回のワークショップ概要文
- 対象者
  - 高校生・大学生が対象
  - ただしタイピングができれば何歳でも可
- 事前にやってきてもらうべきことがあれば記載
- PCはあります
- 女子限定イベント

**Comment by saorio** [comment]
大変細くて申し訳ないんですが、対象者って男性入りませんよね？というのも記載あった方が良いかなと思いました。

**Comment by mahya8585** [comment]
追記しました！

**Comment by mahya8585** [comment]
@MamiSATO さんが叩き作成ちゅう

**Comment by saorio** [comment]
issueを見ていて、どこに書いたら適切かわからない内容なんですが、pythonの言語を知っている人と知らない人がどれくらい来るかにもよりますが、ワークショップの前にpythonという言語の特徴とか(pyladiesの紹介も含め)あるんでしょうか？

**Comment by amacbee** [comment]
他言語とくらべてどういう言語だ的な話はしないと思いますが，Pythonを使うと何が出来る（WebAppが作れるとかPythonで出来てるものの紹介とか）はすると思います！
もちろんPyLadies Tokyoの宣伝もするつもりです〜

**Comment by MamiSATO** [comment]
・各回20名、全て募集をかけてしまっていいか（当日枠残す？）

**Comment by mahya8585** [comment]
本家サイトにもワークショップは事前申し込みが〜と書かれているので、募集自体は20名でかけてしまって良いのではないかと思います。が、いかがでしょう・・・

**Comment by amacbee** [comment]
コメント遅くなりました (___;
各回20名募集かけちゃって下さい！
当日集めるのは可能な限り避けたい（多分埋まらないので当日集めることになるとは思ってます←）

**Comment by amacbee** [comment]
以下のページヘのリンクも載せて下さい．よろしくお願いします！
http://pyladies-tokyo.connpass.com/event/11862/

**Comment by amacbee** [comment]
http://pyladies-tokyo.connpass.com/event/11662/
