### ISSUE TITLE
当日にWindows機をすぐ使える状態にする

### ISSUE THREAD

**Issue by amacbee** [PyLadiesTokyo/girls-tech-fes#70]
- Windows機を起動
- PyCharmを起動

**Comment by nobolis** [comment]
ドキュメント作成しました
Girls-tech-fesWinPC当日作業
https://docs.google.com/document/d/1vZ-skcHpEP4_EMddU2KCYotO6p7dSX_zzrF_2rGcKTA/edit

**Comment by mahya8585** [comment]
手順書を元に作業済み。
ドタバタ劇もありつつ終焉
