### ISSUE TITLE
当日利用する誘導用ポスターを作成

### ISSUE THREAD

**Issue by amacbee** [PyLadiesTokyo/girls-tech-fes#71]
東大側にポスターを貼ってもよいか確認する必要がある

**Comment by saorio** [comment]
文字だけでもいいのですが、t-shirtsと同じロゴとかあれば一緒に印刷したいです。どこかにありますでしょうか。

**Comment by amacbee** [comment]
恐らくまだデザインは完成していないので，issueリンクしておきます

**Comment by nobolis** [comment]
全体の案内図や、誘導は先方が用意するそうです。
個別の企画の面白そうなチラシがあればその方が良いかもとのこと。

と書きながら「ポスターを貼ってよいのか」についての回答をもらっていないことに気がつく（汗）

とりあえずチラシ的なものはあった方が良さそうです。
貼ってよいのかについてはもういちど確認してみますm(_ _)m

**Comment by saorio** [comment]
わかりました。
ご確認お願いします！
3月入りましたけど、人数伸びないですね。。

2015年3月5日木曜日、Katayanagi, Nobukonotifications@github.comさんは書きました:

> 全体の案内図や、誘導は先方が用意するそうです。
> 個別の企画の面白そうなチラシがあればその方が良いかもとのこと。
> 
> と書きながら「ポスターを貼ってよいのか」についての回答をもらっていないことに気がつく（汗）
> 
> とりあえずチラシ的なものはあった方が良さそうです。
> 貼ってよいのかについてはもういちど確認してみますm(_ _)m
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/PyLadiesTokyo/girls-tech-fes/issues/71#issuecomment-77302930
> .

## 

太田 沙織
mail:saori.oota3@gmail.com
tel:080-1296-0494

**Comment by nobolis** [comment]
@saorio 私は9人になってる～♪とよろこんでいました(^^;) 宣伝活動まだあまりしていないので、がんばります！

**Comment by saorio** [comment]
あ、そんなになっていましたか！
増えましたね。

2015年3月5日木曜日、Katayanagi, Nobukonotifications@github.comさんは書きました:

> @saorio https://github.com/saorio 私は9人になってる～♪とよろこんでいました(^^;)
> 宣伝活動まだあまりしていないので、がんばります！
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/PyLadiesTokyo/girls-tech-fes/issues/71#issuecomment-77304350
> .

## 

太田 沙織
mail:saori.oota3@gmail.com
tel:080-1296-0494

**Comment by nobolis** [comment]
先方より回答頂きました：
- 全体案内用のポスターと受付で配布する地図は（主催者側が）用意  
- ポスター的なものを掲示版以外の箇所に貼るのは不可、当日用意する案内ボードの利用は可  
  とのことです。

**Comment by amacbee** [comment]
案内ボードのみであれば，ポスターはいらないかなと思うのですがどうですか？ > @saorio

**Comment by saorio** [comment]
そうですね、建物の様子がわからないので、なんとも言えないのですが、無くても良いですかね。
印刷できる環境があれば前日、当日でも間に合いますね。
あとはTシャツが目印になるかもしれないですし。

**Comment by amacbee** [comment]
そうですね！前日の様子を見て貼る場所 等を確認させて下さいmm
