### ISSUE TITLE
Tシャツ用のデザインを全体に共有

### ISSUE THREAD

**Issue by amacbee** [PyLadiesTokyo/girls-tech-fes#72]
ポスターでも利用する予定 (ref. #71 )

**Comment by uni-q** [comment]
こんな雰囲気で作ろうかなーというポートフォリオっぽいのを作りました。
https://jp.pinterest.com/uni_ishizaki/pyladies-tokyo/

デザイン考えて〜デザイン共有して〜決定するまで、このチケットでやる感じかな。

**Comment by uni-q** [comment]
デザイン共有した。どのデザインにするかも決まった。あとで詳細を書く。

**Comment by saorio** [comment]
pyladies tokyoのロゴと女の子のイメージをお手数なんですが、どこかにアップ頂けますか？掲示ポスター用に使わせて頂きます。

**Comment by uni-q** [comment]
@saorio 別issue立てました。少々お待ちくださいね＞＜ refs #85

このissueは終了したので閉じます。
