### ISSUE TITLE
当日の「全体集合」に関する詳細確認

### ISSUE THREAD

**Issue by nobolis** [PyLadiesTokyo/girls-tech-fes#74]
イベント当日の「全体集合」は代表者のみでよいか、全員参加する必要があるかを東大/AnitaBorgに確認。
確認し次第、当日の流れ #54 に反映してもらう。
ref. #24

**Comment by amacbee** [comment]
（AnitaBorg的な話がどちらに転んだとしても）PyLadies Tokyoスタッフとして全員参加にしたいです．

**Comment by nobolis** [comment]
それでは全員参加の方向で。

**Comment by amacbee** [comment]
よろしくお願いします！

**Comment by amacbee** [comment]
問題なさそうであれば閉じて下さい〜 > @nobolis

**Comment by nobolis** [comment]
先方からその後詳細連絡ないですが、とりあえずこのissueを閉じておきます。
