### ISSUE TITLE
タイムキーピング用の大きい時計の用意

### ISSUE THREAD

**Issue by nobolis** [PyLadiesTokyo/girls-tech-fes#75]
@channel 当日のタイムキーピング用に大きめの時計を持ってこられるかたはいらっしゃいますかー？
ref. #5

**Comment by saorio** [comment]
大きめの時計、あるにこしたことはないけど、スマホのストップウォッチ機能でも良い気がしました。
時間管理って、ふだんのpyladiesはどのようにやられているんでしょう？

2015年2月21日土曜日、Katayanagi, Nobukonotifications@github.comさんは書きました:

> @channel https://github.com/channel
> 当日のタイムキーピング用に大きめの時計を持ってこられるかたはいらっしゃいますかー？
> ref. #5 https://github.com/PyLadiesTokyo/girls-tech-fes/issues/5
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/PyLadiesTokyo/girls-tech-fes/issues/75.

## 

太田 沙織
mail:saori.oota3@gmail.com
tel:080-1296-0494

**Comment by nobolis** [comment]
たとえば、時計を持っている人が腕時計等を確認して時間を合図するとかでもいいかもしれませんね。
私が発表した時のPyLadiesでは時間管理は全くされてなかったですね（自分が何分しゃべったのかも覚えていないです^^;）。

**Comment by amacbee** [comment]
PyLadies Tokyo Meetupは私の方で大雑把に時間管理をしてました．
どちらかというと毎回時間があまってたので，質疑応答や自分の発表で時間調整してた感じです．

今回のイベントは時間が足りなくなる方が濃厚なので，結構しっかり時間管理したいですね。。。(ΦωΦ)
でも，時間管理としては以下の感じで問題無いです．

> 時計を持っている人が腕時計等を確認して時間を合図するとかでもいいかもしれませんね。

**Comment by nobolis** [comment]
ご指摘の通り、今回はきっちり時間管理をする必要があると思います。

講師補佐の中からタイムキーパーを一人決めて、その方にやり方も含めて時間管理を一任するというのがよいかなと思いますが、いかがでしょうか。

PyLadies発表、そういえば練習不足で発表時間がやたら短かった>自分。

**Comment by amacbee** [comment]
これでいきましょう！

> 講師補佐の中からタイムキーパーを一人決めて、その方にやり方も含めて時間管理を一任するというのがよいかなと思いますが、いかがでしょうか。

PyLadiesの発表，よしなに大体の試算で回してて割とうまく測れてるのでNo Problemです笑←

> PyLadies発表、そういえば練習不足で発表時間がやたら短かった>自分。

**Comment by nobolis** [comment]
担当決めのissue #78 を立てた のでこちらはクローズします!
