### ISSUE TITLE
筆記用具の用意について相談

### ISSUE THREAD

**Issue by nobolis** [PyLadiesTokyo/girls-tech-fes#76]
- 当日使用する筆記用具（※）を購入するかあるいは持ち寄りにするか？
- 誰が担当するか？
  を相談したい。

※紙、サインペン、ボールペン、セロテープ（養生用テープ）等
ref. #5

**Comment by amacbee** [comment]
この辺りは個人の持ち寄りでどうにかしたいですね。。。(ΦωΦ)
いくつ持ってくる的な話はもう少し詰めたいですが，前日に私が持ってきます．

**Comment by nobolis** [comment]
持ち寄り了解です。みんな手元にそれなりにあると思いますしねー。私も用意可能です。

数は、ペン類各5本、テープ類2-3巻、紙10枚程度でしょうか。

とりあえずworksheetに適当に数を入れておきますので、もっと必要だよ！とか多すぎ！とか思ったら適当に修正よろしくお願いいたします。

**Comment by amacbee** [comment]
本日確認します

**Comment by uni-q** [comment]
受付で以下のものを、私物から持っていきます。
- ボールペン：2本
- 油性マジック（黒2本、赤1本、青1本、緑1本）
- 養生用テープ：1つ
- ガムテープ：1つ
- 透明セロテープ：1つ
- ハサミ：1つ
- カッター：1つ
- ホチキス（予備の針あり）：2つ
- 紙（上質紙・A4サイズ）：20枚
- ゴミ袋：1枚（ねんのため）

**Comment by uni-q** [comment]
@amacbee 上記の道具で大丈夫そうだと思うんですが、どうでしょう（ぜんぶ同人誌を売るイベントで使ってる道具セットです）
下記のシートにも記入しました。
https://docs.google.com/spreadsheets/d/1dtugWVZ5pBS_u20kF0qDvUlm2y0tOpCCowWE9cOvv1U/edit#gid=0

**Comment by uni-q** [comment]
大丈夫そうなので閉じますね。
