### ISSUE TITLE
名札をつけるかどうかについて相談

### ISSUE THREAD

**Issue by nobolis** [PyLadiesTokyo/girls-tech-fes#77]
当日必要なものリストで「名札」がグレー字になっていましたが、名札をつけるかどうかについて相談ってしましたっけ？
もしこの件について結論が出ているようでしたらご教示くださーい！
結論が出ていないようでしたら、ぜひ話し合いを。

**Comment by amacbee** [comment]
名札は参加者＆サポーターお互いつけたいですね〜
なければ買いたい感じ．どうでしょう？

**Comment by nobolis** [comment]
名札があると声をかけやすいし私もつけた方がよいと思います～

どんな名札にするか、話し合いたいですね。
安く上げるならシールとかに名前を書き込んで見えるところにぺたっとはってもらうのもありかなと私は思うんですが、いかがでしょうか。

**Comment by nobolis** [comment]
#81 を立てたので、こちらはクローズしますね。
