### ISSUE TITLE
当日のタイムキーパー係を決める

### ISSUE THREAD

**Issue by nobolis** [PyLadiesTokyo/girls-tech-fes#78]
ワークショップ当日の時間管理係を決める
ref. 75

**Comment by mahya8585** [comment]
http://stopwatchtimer.yokochou.com/
こういうのをタブレットとかに表示するのどうでしょう
必要であればもってきますよ〜（古いタブレット・・・

**Comment by nobolis** [comment]
いいですね！タブレットを持ち上げる動作も合図になりますし。

**Comment by saorio** [comment]
当日のタイムキーパーですが、
スケジュールのエクセルで、勝手にcinnamonさんに振っていましたが、やれるのかな。。

2015年2月25日水曜日、Katayanagi, Nobukonotifications@github.comさんは書きました:

> いいですね！タブレットを持ち上げる動作も合図になりますし。
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/PyLadiesTokyo/girls-tech-fes/issues/78#issuecomment-75938961
> .

## 

太田 沙織
mail:saori.oota3@gmail.com
tel:080-1296-0494

**Comment by nobolis** [comment]
そうでしたか、気が付いてなくてすみません💦
じゃあとりあえずこのissueは閉じてよさそうですね？

**Comment by saorio** [comment]
ちょっとslackで、cinnamonさんにタイムキーパーokか聞いてみます。
少しお時間下さい。

2015年2月25日水曜日、Katayanagi, Nobukonotifications@github.comさんは書きました:

> そうでしたか、気が付いてなくてすみません💦
> じゃあとりあえずこのissueは閉じてよさそうですね？
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/PyLadiesTokyo/girls-tech-fes/issues/78#issuecomment-75947387
> .

## 

太田 沙織
mail:saori.oota3@gmail.com
tel:080-1296-0494

**Comment by nobolis** [comment]
りょうかいしましたー(^^ゞ

**Comment by saorio** [comment]
cinammonさんに確認して了承頂いたのでcloseします。

**Comment by nobolis** [comment]
了解です、ありがとうございましたー
