### ISSUE TITLE
OAタップの用意について相談

### ISSUE THREAD

**Issue by nobolis** [PyLadiesTokyo/girls-tech-fes#79]
先方では10台分程度しか確保できないとのことなので、こちらで用意する必要がありそうです。
用意できる方はいますかー？

**Comment by amacbee** [comment]
む・・・各自持ち寄りで対応したい感じです(ΦωΦ)

**Comment by nobolis** [comment]
ですよね＞もちより

**Comment by amacbee** [comment]
本日確認します

**Comment by mahya8585** [comment]
@nobolis 3つ穴タップ１つ
@uni-q  3つ穴タップ１つ
@maaya8585 3つ穴タップ１つ

足りない分はどっかで調達していきます。
