### ISSUE TITLE
東大TVの撮影を許可するか相談

### ISSUE THREAD

**Issue by nobolis** [PyLadiesTokyo/girls-tech-fes#80]
当日はイベントに東大TV（※）の撮影が入るそうです。

PyLadiesの企画にこの撮影が入っていいか、確認の連絡がきました。
団体として撮影OKの場合は同意書の作成が必要だそうです。

撮影OKか否か、ご相談したいです。
撮影OKの場合は同意書作成をお願いします > @amacbee 
（とりあえず、同意書issueは立てないでおきます）

（※）東大TVについての詳しい説明はドライブの「東大TV公開までのながれ.pdf」をご参照ください。
以下、一部抜粋：
「東大 TV は、東京大学で開催された公開講座や記念講演などを無料で配信しているオンラインプラットフォームです。学内外のあらゆる人々と東京大学の知的活動を地理的・時間的制約を超えて結び、視聴者の学びを深める一助となることを目指しています。」

**Comment by amacbee** [comment]
お昼に改めて確認します

**Comment by amacbee** [comment]
大変申し訳無いです，本日対応します

**Comment by amacbee** [comment]
公開までの流れを確認しました！
撮影OKです．同意書これから作成します．
