### ISSUE TITLE
名札作成に関する相談

### ISSUE THREAD

**Issue by nobolis** [PyLadiesTokyo/girls-tech-fes#81]
#77　で名札つけたいという話の流れになったので、どのような名札をつけるか相談

**Comment by amacbee** [comment]
そこまでお金もかからない（と思われる）ので，今後も汎用的に使えそうな名札入れを買ってしまって良いかと思います

> どんな名札にするか、話し合いたいですね。
> 安く上げるならシールとかに名前を書き込んで見えるところにぺたっとはってもらうのもありかなと私は思うんですが、いかがでしょうか。

**Comment by saorio** [comment]
シール可愛いくていいかも！

2015年3月12日木曜日、Ai MAKABInotifications@github.comさんは書きました:

> そこまでお金もかからない（と思われる）ので，今後も汎用的に使えそうな名札入れを買ってしまって良いかと思います
> 
> どんな名札にするか、話し合いたいですね。
> 安く上げるならシールとかに名前を書き込んで見えるところにぺたっとはってもらうのもありかなと私は思うんですが、いかがでしょうか。
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/PyLadiesTokyo/girls-tech-fes/issues/81#issuecomment-78403489
> .

## 

太田 沙織
mail:saori.oota3@gmail.com
tel:080-1296-0494

**Comment by amacbee** [comment]
当日の受付担当と確認する ref. #58 
用意するなら受付に置く必要がある

**Comment by amacbee** [comment]
服を傷めたくないという方が想定されるので，首からさげるタイプのやつを用意したいなと思います．その辺は値段と相談ですが， @maaya8585 にお願いしたいですmm

**Comment by mahya8585** [comment]
30個PyLadies Tokyo運営で購入します。
当日までに用意します。今回はとりあえず
- 入れ物だけ用意
- PyLadiesのロゴだけ入れたコピー紙なんかを用意します。
- 当日自分で名前描いてもらおう。
- スタッフ分は印刷して用意しておきます。

**Comment by mahya8585** [comment]
http://www.amazon.co.jp/%E3%82%BD%E3%83%8B%E3%83%83%E3%82%AF-%E3%82%AB%E3%83%A9%E3%83%BC%E3%82%A4%E3%83%99%E3%83%B3%E3%83%88%E5%90%8A%E4%B8%8B%E3%81%92%E5%90%8D%E6%9C%AD-%E5%90%8D%E5%88%BA%E3%82%B5%E3%82%A4%E3%82%BA-50%E6%9E%9A%E5%85%A5-VN-849-W/dp/B004ORZ3CA/ref=pd_cp_office_1

購入だん。

【残タスク】
中に入れる紙を用意する。

**Comment by mahya8585** [comment]
名札入れ届きました(超早)
PyLadies Tokyoの資産としてどっかにメモっておきます。
とりあえず@maaya8585が保管してます。当日中に入れる紙とともにもっていきまーす
