### ISSUE TITLE
当日チューターをするメンバーで手順確認

### ISSUE THREAD

**Issue by amacbee** [PyLadiesTokyo/girls-tech-fes#82]
現時点だと以下のメンバーで作業手順を確認する必要がある
(少なくとも2日前までとかには一応確認しておきたい)
- @amacbee
- @sayadroid 
- @sinamon129 
- @MamiSATO 
- @saorio 
- @nobolis

**Comment by mahya8585** [comment]
午前の部・午後の部の前にMTGで共有済み
