### ISSUE TITLE
イベントstuff 打ち上げ

### ISSUE THREAD

**Issue by mahya8585** [PyLadiesTokyo/girls-tech-fes#9]
翌週のどこかで打ち上げをやる。
- 場所は渋谷近辺
- 調整さんたてる

**Comment by amacbee** [comment]
打ち上げのissue立つの早すぎワロタwww

**Comment by amacbee** [comment]
とりあえず振っておきますmm

**Comment by mahya8585** [comment]
http://www.hotpepper.jp/strJ000689759/

17:30から予約しました

**Comment by amacbee** [comment]
:star:

**Comment by mahya8585** [comment]
本日の打ち上げはキャンセルにしました。
後日再度調整さんたてます。

**Comment by mahya8585** [comment]
調整さんたてずみ。今週中（5/2）をめどにアンケート実施中
