### ISSUE TITLE
アンケート結果の共有 w/ 東大

### ISSUE THREAD

**Issue by nobolis** [PyLadiesTokyo/girls-tech-fes#94]
ワークショップ後アンケートについて、「よろしければ差し支えのない範囲で共有して頂けないでしょうか」とリクエストをいただきました。

**Comment by mahya8585** [comment]
ドライブに溜まってるアンケート結果を必要部分だけ切り出してpdf化。
ドライブに保存して @nobolis へ。

**Comment by nobolis** [comment]
東大に送ったのでクローズします！
